title: "ARCZIP documentation"
description: "ARCZIP documentation and specification"
# theme: minima  # Optional: Use GitHub's built-in theme
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
color_scheme: arcs_theme
logo: "/assets/img/icon.png"
favicon_ico: "/assets/img/favi.ico"
back_to_top: true
back_to_top_text: "Back to top"
search_enabled: true
callouts:
  warning:
    title: Warning
    color: red

aux_links:
  "ARCZIP on GitHub":
    - "https://github.com/ARCZIP/ARCZIP.github.io"
aux_links_new_tab: tru

    
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ARCZIP/ARCZIP.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from



markdown: kramdown  # Default Markdown engine
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - remote theme
  - jekyll-github-metadata

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
