title: "ARCZIP documentation"
description: "ARCZIP documentation and specification"
# theme: minima  # Optional: Use GitHub's built-in theme
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
color_scheme: arcs_theme
logo: "/assets/img/icon.png"
favicon_ico: "/assets/img/favi.ico"
back_to_top: true
back_to_top_text: "Back to top"
search_enabled: true
callouts:
  warning:
    title: Warning
    color: red



markdown: kramdown  # Default Markdown engine
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - remote theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
